-- Run this script in the Supabase SQL Editor to add the missing columns to the settings table
-- It will resolve the "Failed to save settings. Make sure you have run the Supabase schema migration." error

ALTER TABLE settings 
  ADD COLUMN IF NOT EXISTS legal_name text,
  ADD COLUMN IF NOT EXISTS brand_name text,
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS state text,
  ADD COLUMN IF NOT EXISTS country text,
  ADD COLUMN IF NOT EXISTS pincode text,
  ADD COLUMN IF NOT EXISTS pan text,
  ADD COLUMN IF NOT EXISTS cin text,
  ADD COLUMN IF NOT EXISTS msme_no text,
  ADD COLUMN IF NOT EXISTS startup_no text,
  ADD COLUMN IF NOT EXISTS iec_code text,
  ADD COLUMN IF NOT EXISTS business_type text,
  ADD COLUMN IF NOT EXISTS alt_phone text,
  ADD COLUMN IF NOT EXISTS support_email text,
  ADD COLUMN IF NOT EXISTS accounts_email text,
  ADD COLUMN IF NOT EXISTS website text,
  
  ADD COLUMN IF NOT EXISTS branch text,
  ADD COLUMN IF NOT EXISTS upi_id text,
  ADD COLUMN IF NOT EXISTS swift_code text,
  ADD COLUMN IF NOT EXISTS iban text,
  ADD COLUMN IF NOT EXISTS qr_url text,
  
  ADD COLUMN IF NOT EXISTS signature_url text,
  ADD COLUMN IF NOT EXISTS stamp_url text,
  ADD COLUMN IF NOT EXISTS theme_color_primary text,
  ADD COLUMN IF NOT EXISTS theme_color_secondary text,
  ADD COLUMN IF NOT EXISTS font_family text,
  ADD COLUMN IF NOT EXISTS invoice_layout text,
  
  ADD COLUMN IF NOT EXISTS invoice_prefix text,
  ADD COLUMN IF NOT EXISTS invoice_start_no text,
  ADD COLUMN IF NOT EXISTS invoice_padding integer,
  ADD COLUMN IF NOT EXISTS currency text,
  ADD COLUMN IF NOT EXISTS default_gst_rate numeric,
  ADD COLUMN IF NOT EXISTS payment_terms text,
  ADD COLUMN IF NOT EXISTS invoice_footer text,
  ADD COLUMN IF NOT EXISTS invoice_notes text,
  ADD COLUMN IF NOT EXISTS declaration_text text,
  ADD COLUMN IF NOT EXISTS reverse_charge boolean,
  ADD COLUMN IF NOT EXISTS place_of_supply text,
  ADD COLUMN IF NOT EXISTS round_off boolean,
  ADD COLUMN IF NOT EXISTS show_amount_in_words boolean,
  ADD COLUMN IF NOT EXISTS enable_qr boolean,
  ADD COLUMN IF NOT EXISTS enable_signature boolean,
  ADD COLUMN IF NOT EXISTS enable_stamp boolean,
  ADD COLUMN IF NOT EXISTS enable_logo boolean,
  
  ADD COLUMN IF NOT EXISTS gst_type text,
  ADD COLUMN IF NOT EXISTS gst_reg_type text,
  ADD COLUMN IF NOT EXISTS default_sac text,
  ADD COLUMN IF NOT EXISTS default_hsn text,
  
  ADD COLUMN IF NOT EXISTS quotation_prefix text,
  ADD COLUMN IF NOT EXISTS quotation_expiry_days integer,
  ADD COLUMN IF NOT EXISTS quotation_terms text,
  ADD COLUMN IF NOT EXISTS quotation_notes text,
  ADD COLUMN IF NOT EXISTS quote_show_logo boolean,
  ADD COLUMN IF NOT EXISTS quote_show_signature boolean,
  ADD COLUMN IF NOT EXISTS quote_show_stamp boolean,
  
  ADD COLUMN IF NOT EXISTS sender_email text,
  ADD COLUMN IF NOT EXISTS reply_email text,
  ADD COLUMN IF NOT EXISTS bcc_email text,
  ADD COLUMN IF NOT EXISTS email_signature text,
  
  ADD COLUMN IF NOT EXISTS accepted_payments jsonb,
  ADD COLUMN IF NOT EXISTS social_links jsonb,
  
  ADD COLUMN IF NOT EXISTS favicon_url text,
  ADD COLUMN IF NOT EXISTS letterhead_url text,
  ADD COLUMN IF NOT EXISTS watermark_url text;
